DesignStash/DS/Areas/HelpPage/Models/HelpPageApiModel.cs
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Net.Http.Headers;
using System.Web.Http.Description;
using DS.Areas.HelpPage.ModelDescriptions;

namespace DS.Areas.HelpPage.Models
{
    /// <summary>
    /// The model that represents an API displayed on the help page.
    /// </summary>
    public class HelpPageApiModel
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="HelpPageApiModel"/> class.
        /// </summary>
        public HelpPageApiModel()
        {
            UriParameters = new Collection<ParameterDescription>();
            SampleRequests = new Dictionary<MediaTypeHeaderValue, object>();
            SampleResponses = new Dictionary<MediaTypeHeaderValue, object>();
            ErrorMessages = new Collection<string>();
        }

        /// <summary>
        /// Gets or sets the <see cref="ApiDescription"/> that describes the API.
        /// </summary>
        public ApiDescription ApiDescription { get; set; }

        /// <summary>
        /// Gets or sets the <see cref="ParameterDescription"/> collection that describes the URI parameters for the API.
        /// </summary>
        public Collection<ParameterDescription> UriParameters { get; private set; }

        /// <summary>
        /// Gets or sets the documentation for the request.
        /// </summary>
        public string RequestDocumentation { get; set; }

        /// <summary>
        /// Gets or sets the <see cref="ModelDescription"/> that describes the request body.
        /// </summary>
        public ModelDescription RequestModelDescription { get; set; }

        /// <summary>
        /// Gets the request body parameter descriptions.
        /// </summary>
        public IList<ParameterDescription> RequestBodyParameters
        {
            get
            {
                return GetParameterDescriptions(RequestModelDescription);
            }
        }

        /// <summary>
        /// Gets or sets the <see cref="ModelDescription"/> that describes the resource.
        /// </summary>
        public ModelDescription ResourceDescription { get; set; }

        /// <summary>
        /// Gets the resource property descriptions.
        /// </summary>
        public IList<ParameterDescription> ResourceProperties
        {
            get
            {
                return GetParameterDescriptions(ResourceDescription);
            }
        }

        /// <summary>
        /// Gets the sample requests associated with the API.
        /// </summary>
        public IDictionary<MediaTypeHeaderValue, object> SampleRequests { get; private set; }

        /// <summary>
        /// Gets the sample responses associated with the API.
        /// </summary>
        public IDictionary<MediaTypeHeaderValue, object> SampleResponses { get; private set; }

        /// <summary>
        /// Gets the error messages associated with this model.
        /// </summary>
        public Collection<string> ErrorMessages { get; private set; }

        private static IList<ParameterDescription> GetParameterDescriptions(ModelDescription modelDescription)
        {
            ComplexTypeModelDescription complexTypeModelDescription = modelDescription as ComplexTypeModelDescription;
            if (complexTypeModelDescription != null)
            {
                return complexTypeModelDescription.Properties;
            }

            CollectionModelDescription collectionModelDescription = modelDescription as CollectionModelDescription;
            if (collectionModelDescription != null)
            {
                complexTypeModelDescription = collectionModelDescription.ElementDescription as ComplexTypeModelDescription;
                if (complexTypeModelDescription != null)
                {
                    return complexTypeModelDescription.Properties;
                }
            }

            return null;
        }
    }
}

DesignStash/DS/Areas/HelpPage/Controllers/HelpController.cs
using System;
using System.Web.Http;
using System.Web.Mvc;
using DS.Areas.HelpPage.ModelDescriptions;
using DS.Areas.HelpPage.Models;

namespace DS.Areas.HelpPage.Controllers
{
    /// <summary>
    /// The controller that will handle requests for the help page.
    /// </summary>
    public class HelpController : Controller
    {
        private const string ErrorViewName = "Error";

        public HelpController()
            : this(GlobalConfiguration.Configuration)
        {
        }

        public HelpController(HttpConfiguration config)
        {
            Configuration = config;
        }

        public HttpConfiguration Configuration { get; private set; }

        public ActionResult Index()
        {
            ViewBag.DocumentationProvider = Configuration.Services.GetDocumentationProvider();
            return View(Configuration.Services.GetApiExplorer().ApiDescriptions);
        }

        public ActionResult Api(string apiId)
        {
            if (!String.IsNullOrEmpty(apiId))
            {
                HelpPageApiModel apiModel = Configuration.GetHelpPageApiModel(apiId);
                if (apiModel != null)
                {
                    return View(apiModel);
                }
            }

            return View(ErrorViewName);
        }

        public ActionResult ResourceModel(string modelName)
        {
            if (!String.IsNullOrEmpty(modelName))
            {
                ModelDescriptionGenerator modelDescriptionGenerator = Configuration.GetModelDescriptionGenerator();
                ModelDescription modelDescription;
                if (modelDescriptionGenerator.GeneratedModels.TryGetValue(modelName, out modelDescription))
                {
                    return View(modelDescription);
                }
            }

            return View(ErrorViewName);
        }
    }
}

DesignStash/DS/Controllers/PatternLibraryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DS.Controllers
{
    public class PatternLibraryController : Controller
    {
        // GET: DS
        [Route("")]
        public ActionResult Index()
        {
            return View();
        }

        [Route("Theme")]
        public ActionResult Theme(string name, string display)
        {
            ViewBag.Title = display + " Theme";
            ViewBag.Project = name;
            return View();
        }

        [Route("Preview")]
        public ActionResult Preview(string theme = null, string pl = null, string pg = null, string pn = null)
        {
            ViewBag.theme = theme;
            ViewBag.patternLevel = pl;
            ViewBag.patternGroup = pg;
            ViewBag.patternName = pn;
            return View();
        }
    }
}

DesignStash/DS/Views/PatternLibrary/DesignStashTheme.cshtml
@{
    ViewBag.Title = "Design Stash Theme";
    ViewBag.Project = "DesignStash";
}

@section Styles {
    <link href="~/External_Library/DesignStash/designstash-styles.min.css" rel="stylesheet" />
}

<div ng-controller="PatternsController as patternsCtrl" ng-init="patternsCtrl.init('@ViewBag.Project', 'atoms')">
    <div class="pl-group-container" ng-repeat="pattern in patternsCtrl.patterns">
        <div id="pl-{{pattern.group}}" class="pl-group-text">{{pattern.display}}</div>
        <div layout="row" layout-xs="column" layout-wrap>
            <div class="pl-info-container" flex="{{component.width == 'full' ? 100:50}}" flex-xs="100" ng-repeat="component in pattern.components">
                <div id="pl-{{pattern.group}}-{{component.name}}" class="pl-component-text">{{component.display}}</div>
                <div class="pl-sample-container">
                    <div class="pl-demo-container" ng-include="patternsCtrl.getPatternSrc(pattern.group, component.name)">

                    </div>
                    <div ng-class="component.showCode ? 'pl-code-container-open':'pl-code-container-close'">
                        <div class="pl-code">{{patternsCtrl.getCode(pattern.group, component.name)}}</div>
                    </div>
                    <div class="pl-button-container">
                        <a class="pl-button" ng-click="patternsCtrl.toggleShowCode($parent.$index, $index)"><span ng-hide="component.showCode">SHOW</span><span ng-show="component.showCode">HIDE</span> SAMPLE CODE</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div ng-controller="PatternsController as patternsCtrl" ng-init="patternsCtrl.init('@ViewBag.Project', 'molecules')">
    <div class="pl-group-container" ng-repeat="pattern in patternsCtrl.patterns">
        <div id="pl-{{pattern.group}}" class="pl-group-text">{{pattern.display}}</div>
        <div layout="row" layout-xs="column" layout-wrap>
            <div class="pl-info-container" flex="{{component.width == 'full' ? 100:50}}" flex-xs="100" ng-repeat="component in pattern.components">
                <div id="pl-{{pattern.group}}-{{component.name}}" class="pl-component-text">{{component.display}}</div>
                <div class="pl-sample-container">
                    <div class="pl-demo-container" ng-include="patternsCtrl.getPatternSrc(pattern.group, component.name)">

                    </div>
                    <div ng-class="component.showCode ? 'pl-code-container-open':'pl-code-container-close'">
                        <div class="pl-code">{{patternsCtrl.getCode(pattern.group, component.name)}}</div>
                    </div>
                    <div class="pl-button-container">
                        <a class="pl-button" ng-click="patternsCtrl.toggleShowCode($parent.$index, $index)"><span ng-hide="component.showCode">SHOW</span><span ng-show="component.showCode">HIDE</span> SAMPLE CODE</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div ng-controller="PatternsController as patternsCtrl" ng-init="patternsCtrl.init('@ViewBag.Project', 'organisms')">
    <div class="pl-group-container" ng-repeat="pattern in patternsCtrl.patterns">
        <div id="pl-{{pattern.group}}" class="pl-group-text">{{pattern.display}}</div>
        <div layout="row" layout-xs="column" layout-wrap>
            <div class="pl-info-container" flex="{{component.width == 'full' ? 100:50}}" flex-xs="100" ng-repeat="component in pattern.components">
                <div id="pl-{{pattern.group}}-{{component.name}}" class="pl-component-text">{{component.display}}</div>
                <div class="pl-sample-container">
                    <div class="pl-demo-container" ng-hide="component.width === 'page'" ng-include="patternsCtrl.getPatternSrc(pattern.group, component.name)">

                    </div>
                    <div class="pl-demo-container" ng-show="component.width === 'page'">
                        This pattern needs to be viewed in full page. <a ng-href="{{'/Theme/DesignStash/Preview?pl=organisms&pg=' + pattern.group + '&pn=' + component.name}}">Click here to view in full page.</a>
                    </div>
                    <div ng-class="component.showCode ? 'pl-code-container-open':'pl-code-container-close'">
                        <div class="pl-code">{{patternsCtrl.getCode(pattern.group, component.name)}}</div>
                    </div>
                    <div class="pl-button-container">
                        <a class="pl-button" ng-click="patternsCtrl.toggleShowCode($parent.$index, $index)"><span ng-hide="component.showCode">SHOW</span><span ng-show="component.showCode">HIDE</span> SAMPLE CODE</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script src="~/External_Library/DesignStash/designstash-scripts.min.js"></script>
}

DesignStash/DS/Views/PatternLibrary/Index.cshtml
@{ Layout = "~/Views/Shared/_HomeLayout.cshtml"; }

<div ng-controller="HomeController as homeCtrl" ng-init="homeCtrl.init()">
    <div class="pl-header-container tk-source-code-pro">
        <h1>Select A Theme</h1>
    </div>
    <div class="pl-patternlibraries-list-container" layout="row" layout-align="center center" layout-wrap>
        <md-card flex="100" flex-gt-sm="45" ng-repeat="theme in homeCtrl.themes">
            <md-button class="md-primary" ng-href="@Url.Action("Theme", "PatternLibrary")?name={{theme.name}}&display={{theme.display}}" target="" ng-disabled="">
                <md-card-content layout="row" layout-align="center center">
                    <div class="card-media">{{theme.display}}</div>
                </md-card-content>
            </md-button>
        </md-card>
    </div>
</div>

@section Scripts {
    <script src="~/External_Library/DesignStash/designstash-scripts.min.js"></script>
}

DesignStash/DS/Views/PatternLibrary/Preview.cshtml
@{
    ViewBag.Title = "Preview";
    Layout = "~/Views/Shared/_HomeLayout.cshtml";
}

@if (ViewBag.theme != null)
{
    @section Styles {
        <link href="~/External_Library/@ViewBag.theme/@ViewBag.theme-styles.min.css" rel="stylesheet" />
    }

    <div ng-controller="PatternsController as patternsCtrl"
         ng-init="patternsCtrl.init('@ViewBag.theme', '@ViewBag.patternLevel')"
         ng-include="patternsCtrl.getPatternSrc('@ViewBag.patternGroup', '@ViewBag.patternName')"
         class="pl-render-body"
         layout="column"
         ng-cloak>

    </div>

    @section Scripts {
        <script src="~/External_Library/@ViewBag.theme/@ViewBag.theme-scripts.min.js"></script>
    }
}
else
{
    @section Styles {
        <link href="~/External_Library/DesignStash/designstash-styles.min.css" rel="stylesheet" />
    }

    <div class="pl-render-body" ng-controller="HomeController as homeCtrl" layout="column" ng-cloak>
        @* vv Place HTML Here vv *@
        Test
        @* ^^ Place HTML Here ^^ *@
    </div>

    @section Scripts {
        <script src="~/External_Library/DesignStash/designstash-scripts.min.js"></script>
    }
}

DesignStash/DS/Views/PatternLibrary/Theme.cshtml
@section Styles {
    <link href="~/External_Library/@ViewBag.Project/@ViewBag.Project-styles.min.css" rel="stylesheet" />
}

<div>
    <h2>How to Use</h2>
    <ol>
        <li>Deploy this Web App.</li>
        <li>Add the minified stylesheet <span class="pl-inline-code">{{ getMinifiedURL('@ViewBag.Project', 'style') }}</span> in your website.</li>
        <li>Add the minified javascript <span class="pl-inline-code">{{ getMinifiedURL('@ViewBag.Project', 'script') }}</span>  in your website</li>
        <li>Start copying the code from below.</li>
    </ol>
</div>

<div ng-controller="PatternsController as patternsCtrl" ng-init="patternsCtrl.init('@ViewBag.Project', 'atoms')">
    <div class="pl-group-container" ng-repeat="pattern in patternsCtrl.patterns">
        <div id="pl-{{pattern.group}}" class="pl-group-text">{{pattern.display}}</div>
        <div layout="row" layout-xs="column" layout-wrap>
            <div class="pl-info-container" flex="{{component.width == 'full' ? 100:50}}" flex-xs="100" ng-repeat="component in pattern.components">
                <div id="pl-{{pattern.group}}-{{component.name}}" class="pl-component-text">{{component.display}}</div>
                <div class="pl-sample-container">
                    <div class="pl-demo-container" ng-include="patternsCtrl.getPatternSrc(pattern.group, component.name)">

                    </div>
                    <div ng-class="component.showCode ? 'pl-code-container-open':'pl-code-container-close'">
                        <div class="pl-code">{{patternsCtrl.getCode(pattern.group, component.name)}}</div>
                    </div>
                    <div class="pl-button-container">
                        <a class="pl-button" ng-click="patternsCtrl.toggleShowCode($parent.$index, $index)"><span ng-hide="component.showCode">SHOW</span><span ng-show="component.showCode">HIDE</span> SAMPLE CODE</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div ng-controller="PatternsController as patternsCtrl" ng-init="patternsCtrl.init('@ViewBag.Project', 'molecules')">
    <div class="pl-group-container" ng-repeat="pattern in patternsCtrl.patterns">
        <div id="pl-{{pattern.group}}" class="pl-group-text">{{pattern.display}}</div>
        <div layout="row" layout-xs="column" layout-wrap>
            <div class="pl-info-container" flex="{{component.width == 'full' ? 100:50}}" flex-xs="100" ng-repeat="component in pattern.components">
                <div id="pl-{{pattern.group}}-{{component.name}}" class="pl-component-text">{{component.display}}</div>
                <div class="pl-sample-container">
                    <div class="pl-demo-container" ng-include="patternsCtrl.getPatternSrc(pattern.group, component.name)">

                    </div>
                    <div ng-class="component.showCode ? 'pl-code-container-open':'pl-code-container-close'">
                        <div class="pl-code">{{patternsCtrl.getCode(pattern.group, component.name)}}</div>
                    </div>
                    <div class="pl-button-container">
                        <a class="pl-button" ng-click="patternsCtrl.toggleShowCode($parent.$index, $index)"><span ng-hide="component.showCode">SHOW</span><span ng-show="component.showCode">HIDE</span> SAMPLE CODE</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div ng-controller="PatternsController as patternsCtrl" ng-init="patternsCtrl.init('@ViewBag.Project', 'organisms')">
    <div class="pl-group-container" ng-repeat="pattern in patternsCtrl.patterns">
        <div id="pl-{{pattern.group}}" class="pl-group-text">{{pattern.display}}</div>
        <div layout="row" layout-xs="column" layout-wrap>
            <div class="pl-info-container" flex="{{component.width == 'full' ? 100:50}}" flex-xs="100" ng-repeat="component in pattern.components">
                <div id="pl-{{pattern.group}}-{{component.name}}" class="pl-component-text">{{component.display}}</div>
                <div class="pl-sample-container">
                    <div class="pl-demo-container" ng-hide="component.width === 'page'" ng-include="patternsCtrl.getPatternSrc(pattern.group, component.name)">

                    </div>
                    <div class="pl-demo-container" ng-show="component.width === 'page'">
                        This pattern needs to be viewed in full page. <a ng-href="{{'Preview?theme=' + patternsCtrl.project + '&pl=organisms&pg=' + pattern.group + '&pn=' + component.name}}">Click here to view in full page.</a>
                    </div>
                    <div ng-class="component.showCode ? 'pl-code-container-open':'pl-code-container-close'">
                        <div class="pl-code">{{patternsCtrl.getCode(pattern.group, component.name)}}</div>
                    </div>
                    <div class="pl-button-container">
                        <a class="pl-button" ng-click="patternsCtrl.toggleShowCode($parent.$index, $index)"><span ng-hide="component.showCode">SHOW</span><span ng-show="component.showCode">HIDE</span> SAMPLE CODE</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script src="~/External_Library/@ViewBag.Project/@ViewBag.Project-theme.min.js"></script>
}

DesignStash/DS/Views/Shared/_HomeLayout.cshtml
@{
    String PLTypeKitURL = System.Web.Configuration.WebConfigurationManager.AppSettings["PL_TypeKitURL"];
    String MaterialIconsURL = System.Web.Configuration.WebConfigurationManager.AppSettings["MaterialIconsURL"];
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Design Stash</title>
    <link rel="icon" href="~/favicon.ico" />
    <link href="~/Bundles/Styles/libraries-bundle.min.css" rel="stylesheet" />
    <link href="~/Content/Site.css" rel="stylesheet" />
    <link href="~/Content/home.css" rel="stylesheet" />
    <link href="@MaterialIconsURL" rel="stylesheet">
    <link href="@PLTypeKitURL" rel="stylesheet" />
    @RenderSection("Styles", false)
</head>
<body ng-app="PLApp" ng-cloak>

    @RenderBody()

    <script src="~/Bundles/Scripts/libraries-bundle.min.js"></script>
    <script src="~/Bundles/Scripts/core-bundle.min.js"></script>
    <script src="~/Scripts/Controllers/home.controller.js"></script>
    @RenderSection("Scripts", false)
</body>
</html>

DesignStash/DS/Views/Shared/_Layout.cshtml
@{
    String PLTypeKitURL = System.Web.Configuration.WebConfigurationManager.AppSettings["PL_TypeKitURL"];
    String MaterialIconsURL = System.Web.Configuration.WebConfigurationManager.AppSettings["MaterialIconsURL"];
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Design Stash</title>
    <link rel="icon" href="~/favicon.ico" />
    <link href="~/Bundles/Styles/libraries-bundle.min.css" rel="stylesheet" />
    <link href="~/Content/Site.css" rel="stylesheet" />
    <link href="@MaterialIconsURL" rel="stylesheet">
    <link href="@PLTypeKitURL" rel="stylesheet" />
    @RenderSection("Styles", false)
</head>
<body ng-app="PLApp" ng-cloak>
    <div class="body-container" ng-controller="PatternLibraryController as patLibCtrl" layout="column" ng-cloak>
        <section layout="row" flex>
            <md-sidenav class="md-sidenav-left pl-sidenav-left"
                        md-is-locked-open="$mdMedia('gt-sm')"
                        md-component-id="pl-sidenav-left"
                        md-whiteframe="4">
                <md-toolbar class="md-theme-indigo">
                    <h1 class="md-toolbar-tools">
                        <md-button hide-gt-sm ng-click="toggleSideNavLeft('pl-sidenav-left')" class="md-icon-button"><i class="material-icons">arrow_back</i></md-button>
                        &nbsp;
                        <md-button class="md-icon-button" href="/"><i class="material-icons">home</i></md-button>
                        &nbsp;
                        @ViewBag.Title
                    </h1>
                </md-toolbar>
                <md-content class="pl-sidenav-container" ng-controller="SideNavController as sideNavCtrl" ng-init="sideNavCtrl.init('@ViewBag.Project')">
                    <div class="pl-sidenav-item-container" ng-if="sideNavCtrl.atoms.length > 0 && sideNavCtrl.atoms != null">
                        <div class="pl-sidenav-item">
                            <a href="#pl-atoms">Atoms</a>
                        </div>
                        <div class="pl-sidenav-sub-item-container">
                            <div class="pl-sidenav-sub-item" ng-repeat="atom in sideNavCtrl.atoms">
                                <a ng-href="#pl-{{atom.group}}">{{atom.display}}</a>
                            </div>
                        </div>
                    </div>
                    <div class="pl-sidenav-item-container" ng-if="sideNavCtrl.molecules.length > 0 && sideNavCtrl.molecules != null">
                        <div class="pl-sidenav-item">
                            <a href="#pl-molecules">Molecules</a>
                        </div>
                        <div class="pl-sidenav-sub-item-container">
                            <div class="pl-sidenav-sub-item" ng-repeat="molecule in sideNavCtrl.molecules">
                                <a ng-href="#pl-{{molecule.group}}">{{molecule.display}}</a>
                            </div>
                        </div>
                    </div>
                    <div class="pl-sidenav-item-container" ng-if="sideNavCtrl.organisms.length > 0 && sideNavCtrl.organisms != null">
                        <div class="pl-sidenav-item">
                            <a href="#pl-organisms">Organisms</a>
                        </div>
                        <div class="pl-sidenav-sub-item-container">
                            <div class="pl-sidenav-sub-item" ng-repeat="organism in sideNavCtrl.organisms">
                                <a ng-href="#pl-{{organism.group}}">{{organism.display}}</a>
                            </div>
                        </div>
                    </div>
                    <div class="pl-sidenav-item-container" ng-if="sideNavCtrl.templates.length > 0 && sideNavCtrl.templates != null">
                        <div class="pl-sidenav-item">
                            <a href="#pl-templates">Templates</a>
                        </div>
                        <div class="pl-sidenav-sub-item-container">
                            <div class="pl-sidenav-sub-item" ng-repeat="template in sideNavCtrl.templates">
                                <a ng-href="#pl-{{template.group}}">{{template.display}}</a>
                            </div>
                        </div>
                    </div>
                </md-content>
            </md-sidenav>

            <md-content flex>
                <md-toolbar hide-gt-sm>
                    <div class="md-toolbar-tools">
                        <md-button ng-click="toggleSideNavLeft('pl-sidenav-left')" class="md-icon-button"><i class="material-icons">menu</i></md-button>
                    </div>
                </md-toolbar>

                <md-content layout-padding>
                    @RenderBody()
                </md-content>
            </md-content>
        </section>
    </div>

    <script src="~/Bundles/Scripts/libraries-bundle.min.js"></script>
    <script src="~/Bundles/Scripts/core-bundle.min.js"></script>
    @RenderSection("Scripts", false)
</body>
</html>